### ISSUE TITLE
minifier plugin is not starting in dotCMS 4.2.2

### ISSUE THREAD

**Issue by nafihaque** [isaaceindhoven/isaac-dotcms-minifier#1]
Cloned code from the following branches 

https://github.com/isaaceindhoven/isaac-dotcms-minifier/tree/dotcms-410
https://github.com/isaaceindhoven/isaac-dotcms-minifier/tree/minifier-static-dynamic

and built out the jar files:

isaac-dotcms-minifier-4.1.1.jar
isaac-dotcms-minifier-dynamic-4.2.1-1.jar (under `/isaac-dotcms-minifier-minifier-static-dynamic/isaac-dotcms-minifier-dynamic/target/`)

Following is the stacktrace I am seeing while starting the plugin:

```
[01/02/18 10:19:07:890 EST] ERROR AJAX.OSGIAJAX: Trying to run method:start
[01/02/18 10:19:07:890 EST] ERROR AJAX.OSGIAJAX: null
javax.servlet.ServletException: Activator start error in bundle nl.isaac.dotcms.plugin.minifier.isaac-dotcms-minifier-dynamic [17]. Unable to start bundle
	at com.dotmarketing.portlets.osgi.AJAX.OSGIAJAX.start(OSGIAJAX.java:122) ~[dotcms_4.2.2_999999.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at com.dotmarketing.portlets.osgi.AJAX.OSGIBaseAJAX.service(OSGIBaseAJAX.java:52) [dotcms_4.2.2_999999.jar:?]
	at com.dotmarketing.portlets.osgi.AJAX.OSGIAJAX.service(OSGIAJAX.java:1) [dotcms_4.2.2_999999.jar:?]
	at com.dotmarketing.servlets.ajax.AjaxAction.doPut(AjaxAction.java:48) [dotcms_4.2.2_999999.jar:?]
	at com.dotmarketing.servlets.ajax.AjaxDirectorServlet.service(AjaxDirectorServlet.java:48) [dotcms_4.2.2_999999.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:203) [dotcms_4.2.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.2.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.2.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:325) [dotcms_4.2.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:110) [dotcms_4.2.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:132) [dotcms_4.2.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.2.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38) [dotcms_4.2.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:108) [dotcms_4.2.2_999999.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: org.osgi.framework.BundleException: Activator start error in bundle nl.isaac.dotcms.plugin.minifier.isaac-dotcms-minifier-dynamic [17].
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2288) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2144) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[org.apache.felix.framework-5.6.2.jar:?]
	at com.dotmarketing.portlets.osgi.AJAX.OSGIAJAX.start(OSGIAJAX.java:115) ~[dotcms_4.2.2_999999.jar:?]
	... 61 more
Caused by: java.lang.RuntimeException: Failed to register servlet MonitoringServlet
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator$1.addingService(ExtendedGenericBundleActivator.java:159) ~[?:?]
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator$1.addingService(ExtendedGenericBundleActivator.java:147) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261) ~[org.apache.felix.framework-5.6.2.jar:?]
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator.addServlet(ExtendedGenericBundleActivator.java:178) ~[?:?]
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator.addServlet(ExtendedGenericBundleActivator.java:140) ~[?:?]
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator.initializeServices(ExtendedGenericBundleActivator.java:95) ~[?:?]
	at nl.isaac.dotcms.minify.osgi.MinifierActivator.start(MinifierActivator.java:20) ~[?:?]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2144) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[org.apache.felix.framework-5.6.2.jar:?]
	at com.dotmarketing.portlets.osgi.AJAX.OSGIAJAX.start(OSGIAJAX.java:115) ~[dotcms_4.2.2_999999.jar:?]
	... 61 more
Caused by: javax.servlet.ServletException: Servlet instance already registered
	at org.apache.felix.http.base.internal.handler.HandlerRegistry.addServlet(HandlerRegistry.java:63) ~[org.apache.felix.http.cometd-2.3.2.jar:2.3.2]
	at org.apache.felix.http.base.internal.service.HttpServiceImpl.registerServlet(HttpServiceImpl.java:102) ~[org.apache.felix.http.cometd-2.3.2.jar:2.3.2]
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator$1.addingService(ExtendedGenericBundleActivator.java:156) ~[?:?]
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator$1.addingService(ExtendedGenericBundleActivator.java:147) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261) ~[org.apache.felix.framework-5.6.2.jar:?]
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator.addServlet(ExtendedGenericBundleActivator.java:178) ~[?:?]
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator.addServlet(ExtendedGenericBundleActivator.java:140) ~[?:?]
	at nl.isaac.dotcms.util.osgi.ExtendedGenericBundleActivator.initializeServices(ExtendedGenericBundleActivator.java:95) ~[?:?]
	at nl.isaac.dotcms.minify.osgi.MinifierActivator.start(MinifierActivator.java:20) ~[?:?]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2144) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[org.apache.felix.framework-5.6.2.jar:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[org.apache.felix.framework-5.6.2.jar:?]
	at com.dotmarketing.portlets.osgi.AJAX.OSGIAJAX.start(OSGIAJAX.java:115) ~[dotcms_4.2.2_999999.jar:?]
	... 61 more
```

**Comment by yasindilekci** [comment]
Hi,

Thanks for your comment.

The dynamic plugin of the minifier is not compatible with dotCMS 4.X due to a bug in dotCMS.

Please use the static plugin instead.

Thank you

**Comment by nafihaque** [comment]
I tried uploading the following 
`/isaac-dotcms-minifier-minifier-static-dynamic/isaac-dotcms-minifier-static/target/isaac-dotcms-minifier-static-4.2.1-1.jar`
Following is the log while I am uploading it:
`[01/02/18 10:57:06:466 EST]  INFO AJAX.OSGIAJAX: OSGI Bundle isaac-dotcms-minifier-static-4.2.1-1.jar Uploaded`
But it never shows up in the list of dynamic plugins in dotCMS

Also in both cases I tried going to the URL:
http://localhost:8080/app/servlets/monitoring/isaac-dotcms-minifier

And I get the following:
dotCMS: Page not found (404 error)
The Page or file you were looking for was not found.
Please make sure that you have typed the correct URL.

There is no error in the browser console or dotcms log.

**Comment by nafihaque** [comment]
I should also mention, when I restarted OSGI framework `isaac-dotcms-minifier-dynamic-4.2.1-1.jar `did start. Following is the log snippet related:
```
==> /opt/dotcms/logs/dotcms.log <==
[01/02/18 10:50:23:265 EST]  INFO osgi.MinifierActivator: Registering Servlet MonitoringServlet on /app/servlets/monitoring/isaac-dotcms-minifier-dynamic

==> /opt/dotcms/tomcatlogs/catalina.out <==
DEBUG: DYNAMIC WIRE: [nl.isaac.dotcms.plugin.minifier.isaac-dotcms-minifier-dynamic [15](R 15.0)] osgi.wiring.package; (osgi.wiring.package=*) -> [org.apache.felix.framework [0](R 0)]
DEBUG: DYNAMIC WIRE: [nl.isaac.dotcms.plugin.minifier.isaac-dotcms-minifier-dynamic [15](R 15.0)] osgi.wiring.package; (osgi.wiring.package=*) -> [org.apache.felix.http.bundle [8](R 8.0)]
DEBUG: DYNAMIC WIRE: [nl.isaac.dotcms.plugin.minifier.isaac-dotcms-minifier-dynamic [15](R 15.0)] osgi.wiring.package; (osgi.wiring.package=*) -> [osgi.cmpn [9](R 9.0)]
DEBUG: DYNAMIC WIRE: [nl.isaac.dotcms.plugin.minifier.isaac-dotcms-minifier-dynamic [15](R 15.0)] osgi.wiring.package; (osgi.wiring.package=*) -> [org.apache.felix.framework [0](R 0)]

==> /opt/dotcms/logs/dotcms.log <==
[01/02/18 10:50:23:305 EST]  INFO osgi.MinifierActivator: Registering PostHook FileChangedPostHook

==> /opt/dotcms/tomcatlogs/catalina.out <==
DEBUG: DYNAMIC WIRE: [nl.isaac.dotcms.plugin.minifier.isaac-dotcms-minifier-dynamic [15](R 15.0)] osgi.wiring.package; (osgi.wiring.package=*) -> [org.apache.felix.framework [0](R 0)]
DEBUG: DYNAMIC WIRE: [nl.isaac.dotcms.plugin.minifier.isaac-dotcms-minifier-dynamic [15](R 15.0)] osgi.wiring.package; (osgi.wiring.package=*) -> [org.apache.felix.framework [0](R 0)]

==> /opt/dotcms/logs/dotcms.log <==
[01/02/18 10:50:23:367 EST]  INFO osgi.MinifierActivator: Added View Tool: jsMinifyTool
[01/02/18 10:50:23:368 EST]  INFO osgi.MinifierActivator: Added View Tool: cssMinifyTool
[01/02/18 10:50:23:369 EST]  INFO osgi.MinifierActivator: Registering Servlet MinifyServlet on /app/servlets/MinifyServlet
[01/02/18 10:50:23:370 EST]  INFO osgi.MinifierActivator: Registering Servlet MinifyProxyServlet on /app/servlets/MinifyProxyServlet

==> /opt/dotcms/tomcatlogs/catalina.out <==
Started bundle: file:/opt/dotcms_4_2_2/dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/felix/load/isaac-dotcms-minifier-dynamic-4.2.1-1.jar
```
But even after that when I try going to the URL:
http://localhost:8080/app/servlets/monitoring/isaac-dotcms-minifier

I get the following:
dotCMS: Page not found (404 error)
The Page or file you were looking for was not found.
Please make sure that you have typed the correct URL.

There is no error in the browser console or dotcms log.

**Comment by nafihaque** [comment]
Hello Yasin,

I was wondering if you had a chance to look at my last response. I am trying to troubleshoot this but I am not as familiar with this code as you are. So it would be great if you could take a look.

Thanks,
Nafi

**Comment by yasindilekci** [comment]
As I mentioned earlier, the dynamic version of this plugin is not compatible with dotCMS 4.X due to a bug in dotCMS. So we've created a temporary branch called 'minifier-static-dynamic' until dotCMS resolves this issue.

Therefore you need to deploy the static version of the minifier plugin. So checkout the 'minifier-static-dynamic' branch, execute `mvn clean package` and use the generated static plugin called 'isaac-dotcms-minifier-static-4.2.1-1', which you can find inside the 'isaac-dotcms-minifier-static/target' folder.

Instructions on how to deploy static plugins in dotCMS can be found [here](https://dotcms.com/docs/latest/deploy-static-plugins)

**Comment by nafihaque** [comment]
Thanks Yasin for your reply. So I tried deploying isaac-dotcms-minifier-static-4.2.1-1 to dotCMS 4.2.2 as a static plugin and still I can't access 
http://localhost:9090/app/servlets/monitoring/isaac-dotcms-minifier
It shows 404 Not Found. I don't see any error in the log. Any idea what I might be missing?

**Comment by yasindilekci** [comment]
You're welcome @nafihaque. The monitoring URL won't work as this feature is only available in the dynamic plugin. Whenever a URL contains 'app' in the path, it means it's pointing to a dynamic plugin.

Anyways, what I recommend you is to test the functionality by applying one of the many examples provided in [the documentation](https://github.com/isaaceindhoven/isaac-dotcms-minifier/wiki)

**Comment by nafihaque** [comment]
Thanks again @yasindilekci . So I tried using a simple use case as following:

$jsMinifyTool.addFiles("/js/jquery.maskedinput.min.js","jsGroup")
$jsMinifyTool.toScriptTag("jsGroup")

And it's not producing expected HTML script tag. It seems like $jsMinifyTool is not getting evaluated and thus none of those API calls are working.

**Comment by yasindilekci** [comment]
What do you see in the page source when you print $jsMinifyTool in the VTL file? Just put $jsMinifyTool in your VTL file and let me know what you see.

**Comment by nafihaque** [comment]
All I see is `$jsMinifyTool`

**Comment by yasindilekci** [comment]
Seems like the ViewTool isn't registered.

Did you execute the undeploy/deploy batch files?

If so, could you please post your full path of the location of the static plugin, including the dotCMS folder name? I need to know the path up to and including the ROOT folder which is inside the plugin folder.

**Comment by nafihaque** [comment]
I tried following to deploy the static plugin 
1. copied isaac-dotcms-minifier-static-4.2.1-1.zip into /opt/dotcms/plugins/
2. Executed /opt/dotcms/bin/undeploy-plugins.sh followed by deploy-plugins.sh
3. Restarted dotCMS

After this I checked /opt/dotcms/dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/lib/ to make sure `isaac-dotcms-minifier-static-4.2.1-1.jar` is there. Does that answer your question?

**Comment by yasindilekci** [comment]
You have to extract the zip file inside /opt/dotcms/plugins after copying. Make sure to use the option 'extract here' or something like that instead of 'extract to ... '.

The full path of the plugin should be /opt/dotcms/plugins/isaac-dotcms-minifier-static

If you do something like 'extract to ....' you'll get an invalid path (plugin name twice): /opt/dotcms/plugins/isaac-dotcms-minifier-static/isaac-dotcms-minifier-static

**Comment by nafihaque** [comment]
One thing I would like to mention the zip file which gets created after I run `mvn clean package` only has java classes. Attached is the zip file..
[isaac-dotcms-minifier-static-4.2.1-1.zip](https://github.com/isaaceindhoven/isaac-dotcms-minifier/files/1749759/isaac-dotcms-minifier-static-4.2.1-1.zip)

**Comment by yasindilekci** [comment]
Weird, in which folder did you execute `mvn clean package`?

**Comment by yasindilekci** [comment]
I'm on a Windows machine, this is the zip file when I execute `mvn clean package` in the root folder: 
[isaac-dotcms-minifier-static-4.2.1-1.zip](https://github.com/isaaceindhoven/isaac-dotcms-minifier/files/1749806/isaac-dotcms-minifier-static-4.2.1-1.zip)

The folder I execute the command in:
![image](https://user-images.githubusercontent.com/10976988/36567984-b7f03688-1828-11e8-865b-5f40e1f4108f.png)

Location of the zip folder:
![image](https://user-images.githubusercontent.com/10976988/36568006-c67e6e68-1828-11e8-8ccf-4f4a0fd13a64.png)

**Comment by nafihaque** [comment]
I executed `mvn clean package` from my mac at the root folder which is i**saac-dotcms-minifier-minifier-static-dynamic** containing following files and folders:
README.md			isaac-dotcms-minifier-dynamic	isaac-dotcms-minifier.iml
isaac-dotcms-minifier-core	isaac-dotcms-minifier-static	pom.xml

I will place your zip file now in plugins folder and try deploying static plugin. I will let you know what I get out of it.

**Comment by nafihaque** [comment]
@yasindilekci it is still not working :(

**Comment by yasindilekci** [comment]
What is the error in the logs? Or what do you see?

**Comment by nafihaque** [comment]
$jsMinifyTool is still not getting evaluated, I see following:

JS MinifyTool: $jsMinifyTool

**Comment by yasindilekci** [comment]
Did you extract the zip file I provided to /opt/dotcms/plugins/isaac-dotcms-minifier-static ? The contents of this folder should be as follows:

![image](https://user-images.githubusercontent.com/10976988/36568520-9ffba150-182a-11e8-8063-c9cac41867c7.png)

Did you stop dotCMS, undeploy/deploy and start it again?

**Comment by nafihaque** [comment]
I did not extract the zip file but I will try that right now. Also, I see only following when I extracted your zip file, let me know if this is correct as I am not seeing some of the folders which you shared above..
<img width="605" alt="screen shot 2018-02-22 at 5 48 59 pm" src="https://user-images.githubusercontent.com/13683652/36568670-d945d4f8-17f8-11e8-9b2b-87852d281194.png">

**Comment by yasindilekci** [comment]
The folder structure shown in the picture is fine, the 'missing' folders are empty anyways so that's probably the reason they're not there. Could you please try to unzip?

**Comment by nafihaque** [comment]
I don't know if we can actually deploy static plugin that way. I am getting following error while deploying with the extracted folder:

compile:
     [echo] Building at: isaac-dotcms-minifier-static at /opt/dotcms/plugins/isaac-dotcms-minifier-static
    [mkdir] Created dir: /opt/dotcms/plugins/isaac-dotcms-minifier-static/build/classes
    [javac] /opt/dotcms/plugins/common.xml:81: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 18 source files to /opt/dotcms/plugins/isaac-dotcms-minifier-static/build/classes

BUILD FAILED
/opt/dotcms/bin/ant/build.xml:629: The following error occurred while executing this line:
/opt/dotcms/bin/ant/build.xml:607: The following error occurred while executing this line:
/opt/dotcms/plugins/common.xml:81: Error running javac compiler

**Comment by yasindilekci** [comment]
Is Java configured properly, including the Java home variable etc.?

**Comment by nafihaque** [comment]
Yes it should be. We have other static plugins which are also being deployed without any issue. Here is another folder in plugins folder:

[dotcms@RotoRooter-VM plugins]$ ls -l com.dotcms.config/
total 52
drwxrwxr-x. 5 dotcms dotcms 4096 Feb 22 22:54 build
-rw-rw-r--. 1 dotcms dotcms   98 Feb 21 20:32 build.xml
drwxrwxr-x. 2 dotcms dotcms 4096 Feb 21 20:32 conf
drwxr-xr-x. 2 dotcms dotcms 4096 Feb 21 20:32 dotcms
drwxr-xr-x. 2 dotcms dotcms 4096 Feb 21 20:32 jsp
drwxr-xr-x. 2 dotcms dotcms 4096 Feb 21 20:32 lib
-rw-rw-r--. 1 dotcms dotcms   84 Feb 21 20:32 MANIFEST.MF
-rw-rw-r--. 1 dotcms dotcms  293 Feb 21 20:32 README.txt
drwxrwxr-x. 4 dotcms dotcms 4096 Feb 21 20:32 ROOT
drwxr-xr-x. 2 dotcms dotcms 4096 Feb 21 20:32 src
drwxr-xr-x. 2 dotcms dotcms 4096 Feb 21 20:32 static_files
drwxr-xr-x. 2 dotcms dotcms 4096 Feb 21 20:32 static_velocity
drwxr-xr-x. 2 dotcms dotcms 4096 Feb 21 20:32 tiny_mce

**Comment by yasindilekci** [comment]
Can you please try the following:

1. open common.xml in /opt/dotcms/plugins
2. scroll down to line 81
3. change fork="true" to fork="false"
4. save, undeploy and deploy again

**Comment by nafihaque** [comment]
I see the following when attempting to deploy again with fork=false

`[dotcms@RotoRooter-VM plugins]$ /opt/dotcms/bin/deploy-plugins.sh 
Using DOTCMS_HOME:   /opt/dotcms
Using JAVA_HOME:       /usr/lib/jvm/jre-1.8.0-openjdk.x86_64
Deploying plugins
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-2.b16.el6_9.x86_64/lib/tools.jar
Buildfile: /opt/dotcms/bin/ant/build.xml

-check-use-file:

use-file:

setup-deploy-location:
     [echo] Deploying plugins to: /opt/dotcms/bin/ant/../../dotserver/tomcat-8.0.18/webapps/ROOT | dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/lib

build-plugins:
      [jar] Building MANIFEST-only jar: /opt/dotcms/plugins/com.dotcms.config/classpath-tmp.jar

clean:
   [delete] Deleting directory /opt/dotcms/plugins/com.dotcms.config/build

compile:
     [echo] Building at: com.dotcms.config at /opt/dotcms/plugins/com.dotcms.config
    [mkdir] Created dir: /opt/dotcms/plugins/com.dotcms.config/build/classes
    [javac] /opt/dotcms/plugins/common.xml:81: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

BUILD FAILED
/opt/dotcms/bin/ant/build.xml:629: The following error occurred while executing this line:
/opt/dotcms/bin/ant/build.xml:607: The following error occurred while executing this line:
/opt/dotcms/plugins/common.xml:81: Unable to find a javac compiler;
com.sun.tools.javac.Main is not on the classpath.
Perhaps JAVA_HOME does not point to the JDK.
It is currently set to "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-2.b16.el6_9.x86_64/jre"`

**Comment by yasindilekci** [comment]
Why is it set to the "JRE" folder? It should point to the "JDK" folder instead.

**Comment by nafihaque** [comment]
I am not sure why it's saying that .. when I printed out java home it shows the following:
[dotcms@RotoRooter-VM plugins]$ echo $JAVA_HOME
/usr/lib/jvm/jre-1.8.0-openjdk.x86_64

**Comment by nafihaque** [comment]
@yasindilekci I really appreciate you put in so much time and effort. This is one of the last thing that I need to get resolved in order finish upgrade to 4.2.2.

Now going back to the issue, do we need to make changes in order to deploy a static plugin? As I mentioned before we have been able to drop jar files for static plugins followed by executing run deploy-plugin.sh. Now I am not fully aware how dotcms integrates the plugin but is there any way we can deploy this plugin without changing any default config?

**Comment by yasindilekci** [comment]
You're welcome, you have to unzip, undeploy/deploy the static plugin in order to make it work.

I've tested the dynamic plugin in dotCMS 4.3 and unfortunately it still does not work, so until dotCMS fixes the bug we have no other choice than deploying it this way...

**Comment by nafihaque** [comment]
Thanks, I'm wondering what else I'd need to do to make it work as a static plugin. I'm still not seeing $jsMinifyTool evaluated.

On Feb 23, 2018 10:36 AM, yasindilekci <notifications@github.com> wrote:

You're welcome, you have to unzip, undeploy/deploy the static plugin in order to make it work.

I tested the dynamic plugin in dotCMS 4.3 and unfortunately it still does not work, so until dotCMS fixes the bug we have no other choice than deploying it this way...

**Comment by yasindilekci** [comment]
Did the undeploy/deploy scripts succeed?

**Comment by nafihaque** [comment]
If you look at dotCMS documentation for deploying static plugin, it says to drop in zip file inside plugins folder and run deploy script. For me deploy script does work with zip file but not with unzipped folder. I'll give the unzipped folder another shot and let you know.

On Feb 23, 2018 10:41 AM, yasindilekci <notifications@github.com> wrote:

Did the undeploy/deploy scripts succeed?

**Comment by nafihaque** [comment]
@yasindilekci does deploying unzipped minifier folder in 4.x as static plugin work for you?

**Comment by nafihaque** [comment]
@yasindilekci  the reason it was pointing to jre but not jdk is, we are not installing JDK in our servers as they do not need to compile any code. Any kind of code compilation is done through CI/CD pipeline taking place on our local environments, not on actual servers which are serving content. This keeps those servers lightweight.

But in order to deploy the minifier I installed jdk on my local VM and ran deploy plugin script. This worked and produced `isaac-dotcms-minifier-static.jar` file which is all we really needed to deploy this plugin as a static plugin. With this successfully installed, $jsMinifyTool is now getting evaluated and all methods are working as before. May I suggest to add to the documentation which version of minifier should be used for dotCMS 4.x and also the disclaimer that dynamic plugin does not work and static plugin is the way to go. Also, it might be helpful for anyone else working on this to know tidbit details of how to install this as a static plugin.

Thanks for your time and assistance throughout.

**Comment by cmaessen** [comment]
I've been following this exchange and with the last response I need to point out the following in the dotCMS documentation regarding [static plugins](https://dotcms.com/docs/latest/deploy-static-plugins):

> These are the steps to deploy a static plugin:
>
> Extract the Zip in the <your_dotCMS>/plugins folder
> 1. Deploy your plugin by running:
> deploy-plugins.sh (Linux, Unix-based)
> deploy-plugins.bat (Windows)
> 2. Restart dotCMS

The documentation says that you need to extract the zip and then start the plugins script. These scripts start a build process. 

That being said I'll have a look this week to see what we can/should clarify.

**Comment by nafihaque** [comment]
@cmaessen thanks for pointing that out.

**Comment by nafihaque** [comment]
One thing I should re-clarify (which also can be derived from above exchanges) is, after cloning the `minifier-static-dynamic` branch and executing `mvn clean package`, the jar file (isaac-dotcms-minifier-static-4.2.1-1.jar) that I got in target folder is not the right jar file which can be deployed as static plugin. 

Instead, I think it is supposed to create a zip file (inside target folder) named `isaac-dotcms-minifier-static-4.2.1-1.zip` having content as following
<img width="598" alt="screen shot 2018-02-27 at 10 05 46 am" src="https://user-images.githubusercontent.com/13683652/36736144-d636c6c2-1ba5-11e8-8e75-dff0123fc952.png">

However in my case, it created that zip file only containing src folder in it. So this might create a roadblock for anyone attempting to deploy it as a static plugin.

So once we have the right zip file ([isaac-dotcms-minifier-static-4.2.1-1.zip](https://github.com/isaaceindhoven/isaac-dotcms-minifier/files/1763438/isaac-dotcms-minifier-static-4.2.1-1.zip)) containing content as the screenshot shows above, following steps should be taken:

- Extract the zip inside dotCMS's plugin folder
- Run deploy-plugins script (make sure there is JDK installed)

**Comment by maarten-daalder-isaac** [comment]
Hi @nafihaque 
There should also be a isaac-dotcms-minifier-static-4.2.1-1.zip (around 7MB) in the target directory.

**Comment by nafihaque** [comment]
@maarten-daalder-isaac I realized its not the folder, it was actually zip file that got generated. But even that zip file did not have all the content. I updated my comment above.

**Comment by maarten-daalder-isaac** [comment]
Could you try the following maven command and uploading the contents of minifier.log to a gist?
`mvn clean package -X -l=minifier.log`

**Comment by nafihaque** [comment]
Here you go @maarten-daalder-isaac 
https://gist.github.com/nafihaque/e8c7291b7afcec80357ccb3c878958b7

**Comment by maarten-daalder-isaac** [comment]
Thanks for the logs.

It looks like the reason is a difference in path resolving on Windows and Unix-like systems in the `maven-assembly-plugin`.

Can you do a pull and try again? My tests unfortunately are only done in a Docker container.

**Comment by nafihaque** [comment]
@maarten-daalder-isaac I pulled the latest and looks like this time it did produce the zip file which contains all the right content. Thanks for looking into it.
